# Exercise real generated install rules without writing to the host prefix.
foreach(required IN ITEMS TEST_BINARY_DIR TEST_SOURCE_DIR TEST_PLUGIN TEST_ECM_DIR)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "Missing install-test input: ${required}")
    endif()
endforeach()
set(work "${TEST_BINARY_DIR}/install check")
file(REMOVE_RECURSE "${work}")
file(MAKE_DIRECTORY "${work}")
set(prefix "${work}/home/.local")
set(nested "${work}/build")
set(stage "${work}/stage")

function(run)
    execute_process(COMMAND ${ARGV} RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Install check failed (${status}): ${ARGV}\n${output}\n${error}")
    endif()
endfunction()

# Keep a multi-prefix list as one argument rather than expanding it through ARGV.
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${TEST_SOURCE_DIR}" -B "${nested}" -G Ninja
    "-DCMAKE_PREFIX_PATH=${TEST_PREFIX_PATH}" "-DECM_DIR=${TEST_ECM_DIR}"
    "-DCMAKE_INSTALL_PREFIX=${prefix}" -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Debug
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Install-test configure failed (${status}):\n${output}\n${error}")
endif()
# Reuse the tested binary. Configuring the install tree need not compile it a second time.
file(MAKE_DIRECTORY "${nested}/lib/plasma/applets")
file(COPY_FILE "${TEST_PLUGIN}" "${nested}/lib/plasma/applets/org.kyaulabs.kodometer.so")
file(SHA256 "${TEST_PLUGIN}" expected_hash)
file(WRITE "${work}/home/preferences" "existing widget selections\n")
file(WRITE "${work}/home/wallet" "existing wallet data\n")

function(check_install destination)
    file(GLOB_RECURSE files LIST_DIRECTORIES FALSE "${stage}/*")
    list(LENGTH files count)
    if(NOT count EQUAL 5)
        message(FATAL_ERROR "Expected only plugin, icon, notifyrc, LICENSE and README; found ${files}")
    endif()
    set(plugin "")
    foreach(path IN LISTS files)
        set(root "${stage}${destination}")
        cmake_path(IS_PREFIX root "${path}" NORMALIZE within_prefix)
        if(NOT within_prefix)
            message(FATAL_ERROR "Install escaped requested prefix: ${path}")
        endif()
        if(path MATCHES "/plasma/applets/org\\.kyaulabs\\.kodometer\\.so$")
            set(plugin "${path}")
        endif()
    endforeach()
    if(NOT plugin)
        message(FATAL_ERROR "Installed plugin is missing")
    endif()
    file(SHA256 "${plugin}" actual_hash)
    if(NOT actual_hash STREQUAL expected_hash)
        message(FATAL_ERROR "Upgrade did not replace the installed plugin")
    endif()
    foreach(pair IN ITEMS "applet/kodometer.notifyrc|share/knotifications6/kodometer.notifyrc"
                          "branding/kodometer-brand-pack/icons/app-tile-dark.svg|share/icons/hicolor/scalable/apps/kodometer.svg"
                          "LICENSE|share/doc/kodometer/LICENSE" "README.md|share/doc/kodometer/README.md")
        string(REPLACE "|" ";" pair "${pair}")
        list(GET pair 0 source)
        list(GET pair 1 installed)
        file(SHA256 "${TEST_SOURCE_DIR}/${source}" expected)
        file(SHA256 "${stage}${destination}/${installed}" actual)
        if(NOT actual STREQUAL expected)
            message(FATAL_ERROR "Installed resource differs: ${installed}")
        endif()
    endforeach()
    file(READ "${work}/home/preferences" preferences)
    file(READ "${work}/home/wallet" wallet)
    if(NOT preferences STREQUAL "existing widget selections\n" OR
       NOT wallet STREQUAL "existing wallet data\n")
        message(FATAL_ERROR "Install changed existing user data")
    endif()
    set(installed_plugin "${plugin}" PARENT_SCOPE)
endfunction()

run("${CMAKE_COMMAND}" -E env "DESTDIR=${stage}" "${CMAKE_COMMAND}" --install "${nested}")
check_install("${prefix}")
# A loadable previous binary with different bytes must be replaced on upgrade.
file(APPEND "${installed_plugin}" "previous installation marker")
run(touch -d @1 "${installed_plugin}")
run("${CMAKE_COMMAND}" -E env "DESTDIR=${stage}" "${CMAKE_COMMAND}" --install "${nested}")
check_install("${prefix}")
file(REMOVE_RECURSE "${stage}")
set(relocated "${work}/relocated prefix")
run("${CMAKE_COMMAND}" -E env "DESTDIR=${stage}" "${CMAKE_COMMAND}" --install "${nested}" --prefix "${relocated}")
check_install("${relocated}")
