# Native packages are built inside their target distro, never from the Arch binary.
set(packaging_root "${CMAKE_CURRENT_LIST_DIR}/../packaging")
file(READ "${packaging_root}/targets.json" package_targets)
string(JSON target_count LENGTH "${package_targets}")
math(EXPR target_last "${target_count} - 1")
set(package_kind "")
foreach(index RANGE ${target_last})
    string(JSON target_id GET "${package_targets}" ${index} id)
    if(target_id STREQUAL KODOMETER_PACKAGE_TARGET)
        string(JSON package_kind GET "${package_targets}" ${index} kind)
        string(JSON distro_version GET "${package_targets}" ${index} version)
    endif()
endforeach()
if(NOT package_kind MATCHES "^(deb|rpm)$")
    message(FATAL_ERROR "Choose a supported Ubuntu or Fedora KODOMETER_PACKAGE_TARGET")
endif()
set(CPACK_PACKAGE_NAME kodometer)
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_VENDOR kyaulabs)
set(CPACK_PACKAGE_CONTACT "kyau <kyau@kyau.net>")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Native AI provider usage meter for KDE Plasma")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/kyaulabs/kodometer")
set(CPACK_PACKAGING_INSTALL_PREFIX /usr)
set(CPACK_PACKAGE_DIRECTORY "${CMAKE_BINARY_DIR}/packages")
set(CPACK_STRIP_FILES ON)
set(CPACK_RESOURCE_FILE_LICENSE "${packaging_root}/../LICENSE")

if(package_kind STREQUAL "deb")
    set(CPACK_GENERATOR DEB)
    set(CPACK_PACKAGE_FILE_NAME "kodometer_${PROJECT_VERSION}-1ubuntu${distro_version}_amd64")
    set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE amd64)
    set(CPACK_DEBIAN_PACKAGE_RELEASE "1ubuntu${distro_version}")
    set(CPACK_DEBIAN_PACKAGE_SECTION kde)
    set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
    # QML imports and the wallet daemon cannot be inferred from ELF dependencies.
    set(CPACK_DEBIAN_PACKAGE_DEPENDS "plasma-workspace (>= 4:6.4), kwallet6, qml6-module-org-kde-kirigami, qml6-module-qtquick-controls, qml6-module-qtquick-layouts, qml6-module-qtquick-dialogs, qml6-module-qtqml-workerscript, qt6-qpa-plugins")
    file(READ "${packaging_root}/../LICENSE" package_license)
    string(REPLACE "\n" "\n " package_license "${package_license}")
    string(REPLACE "\n \n" "\n .\n" package_license "${package_license}")
    configure_file("${packaging_root}/debian/copyright.in" "${CMAKE_BINARY_DIR}/copyright" @ONLY)
    install(FILES "${CMAKE_BINARY_DIR}/copyright" DESTINATION "${KDE_INSTALL_DATADIR}/doc/kodometer")
else()
    set(CPACK_GENERATOR RPM)
    set(CPACK_PACKAGE_FILE_NAME "kodometer-${PROJECT_VERSION}-1.fc${distro_version}.x86_64")
    set(CPACK_RPM_PACKAGE_ARCHITECTURE x86_64)
    set(CPACK_RPM_PACKAGE_RELEASE "1.fc${distro_version}")
    set(CPACK_RPM_PACKAGE_LICENSE AGPL-3.0-only)
    set(CPACK_RPM_PACKAGE_GROUP Applications/System)
    set(CPACK_RPM_PACKAGE_AUTOREQ ON)
    # The applet is a private plugin, not a library interface for other packages.
    set(CPACK_RPM_PACKAGE_AUTOPROV OFF)
    set(CPACK_RPM_PACKAGE_REQUIRES "plasma-workspace >= 6.4, kf6-kirigami, kf6-kwallet, qt6-qtdeclarative")
    set(CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION
        /usr/lib/qt6 /usr/lib/qt6/plugins /usr/lib/qt6/plugins/plasma
        /usr/lib/qt6/plugins/plasma/applets
        /usr/lib64/qt6 /usr/lib64/qt6/plugins /usr/lib64/qt6/plugins/plasma
        /usr/lib64/qt6/plugins/plasma/applets /usr/share/knotifications6)
    set(CPACK_RPM_USER_FILELIST "%license /usr/share/doc/kodometer/LICENSE")
endif()
include(CPack)
